export interface TTestElement {
    group: string;
    key: string;
    name: string;
    description: string;
    games: string[];
    dependsOn: string[];
}

export default [
    {
        group: 'fling',
        key: 'fling-up',
        name: 'Fling Up',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'fling',
        key: 'fling-infinite',
        name: 'Fling Infinite',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'fling',
        key: 'fling-forward',
        name: 'Fling Forward',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'gel',
        key: 'gel-repulsion',
        name: 'Repulsion Gel',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'gel',
        key: 'gel-propulsion',
        name: 'Propulsion Gel',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'gel',
        key: 'gel-conversion',
        name: 'Conversion Gel',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'funnel',
        key: 'funnel-push',
        name: 'Funnel pushing forward',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'funnel',
        key: 'funnel-pull',
        name: 'Funnel pulling back',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'laser',
        key: 'laser-provider',
        name: 'Laser Provider',
        description: '',
        games: ['portal2'],
        dependsOn: ['laser-receiver'],
    },
    {
        group: 'laser',
        key: 'laser-checkpoint',
        name: 'Laser Checkpoint',
        description: '',
        games: ['portal2'],
        dependsOn: ['laser-provider'],
    },
    {
        group: 'laser',
        key: 'laser-receiver',
        name: 'Laser Receiver',
        description: '',
        games: ['portal2'],
        dependsOn: ['laser-provider'],
    },
    {
        group: 'pellet',
        key: 'pellet-provider',
        name: 'Pellet Provider',
        description: '',
        games: ['portal1'],
        dependsOn: ['pellet-receiver'],
    },
    {
        group: 'pellet',
        key: 'pellet-receiver',
        name: 'Pellet Receiver',
        description: '',
        games: ['portal1'],
        dependsOn: ['pellet-provider'],
    },
    {
        group: 'laser-wall',
        key: 'laser-wall',
        name: 'Laser Wall',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'lift',
        key: 'lift',
        name: 'Lift',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'lift',
        key: 'scaffold',
        name: 'Scaffold',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'stairs',
        key: 'stairs',
        name: 'Stairs',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'decoration',
        key: 'bottomless-pit',
        name: 'Bottomless Pit',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'decoration',
        key: 'observation-room',
        name: 'Observation Room',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'decoration',
        key: 'behind-the-scenes',
        name: 'Behind the Scenes',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'water',
        key: 'water',
        name: 'Water',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'turret',
        key: 'turret-general',
        name: 'Turret',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'turret',
        key: 'turret-rocket',
        name: 'Rocket',
        description: '',
        games: ['portal1'],
        dependsOn: [],
    },
    {
        group: 'vent',
        key: 'tube-vent',
        name: 'Vent',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'vent',
        key: 'tube-vacuum',
        name: 'VacTube',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'bridge',
        key: 'bridge',
        name: 'Bridge',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'button',
        key: 'button-general',
        name: 'Button',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: ['dropper-cube', 'dropper-sphere'],
    },
    {
        group: 'button',
        key: 'button-cube',
        name: 'Cube Button',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: ['dropper-cube'],
    },
    {
        group: 'button',
        key: 'button-sphere',
        name: 'Sphere Button',
        description: '',
        games: ['portal2'],
        dependsOn: ['dropper-sphere'],
    },
    {
        group: 'button',
        key: 'button-person',
        name: 'Person Button',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'dropper',
        key: 'dropper-cube',
        name: 'Cube Dropper',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'dropper',
        key: 'dropper-reflection',
        name: 'Reflection Cube Dropper',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'dropper',
        key: 'dropper-sphere',
        name: 'Sphere Dropper',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
    {
        group: 'fizzler',
        key: 'fizzler',
        name: 'Fizzler',
        description: '',
        games: ['portal1', 'portal2'],
        dependsOn: [],
    },
    {
        group: 'faithplate',
        key: 'faithplate',
        name: 'Faithplate',
        description: '',
        games: ['portal2'],
        dependsOn: [],
    },
] as TTestElement[];
